#!/usr/bin/env bash
# Single source of truth for the repository's Git rules (PRD §10–§11).
# Sourced by the local hooks in .githooks/ and by the git-policy CI workflow.

# Branch model: long-lived master / pre-release / release/vX.Y.Z, short-lived feature/* and fix/*.
BRANCH_PATTERN='^(master|pre-release|release/v[0-9]+\.[0-9]+\.[0-9]+|feature/[a-z0-9]+(-[a-z0-9]+)*|fix/[a-z0-9]+(-[a-z0-9]+)*)$'
PROTECTED_PATTERN='^(master|pre-release|release/.+)$'

# PRD §11: <type>(<scope>): <short description>, types limited to the PRD list.
COMMIT_TYPES='feat|fix|refactor|test|docs|chore|build'
HEADER_PATTERN="^(${COMMIT_TYPES})\(([a-z0-9]+(-[a-z0-9]+)*)\): (.+)$"
MAX_HEADER_LENGTH=72
MIN_DESCRIPTION_WORDS=3
# PRD §11 explicitly bans these as commit messages; they carry no information in any position.
BANNED_WORDS_PATTERN='(^|[^a-z])(final|latest|asdf|wip|tmp|temp|misc|stuff|working now|minor changes|some changes)([^a-z]|$)'

# Files that must never be committed.
FORBIDDEN_FILES_PATTERN='(^|/)\.env$|(^|/)\.env\.(local|development|production|test)$|^docs/PRD\.md$|\.pem$|(^|/)id_(rsa|ed25519)$'

# High-signal secret shapes. Placeholder/local DB URLs are allowed (see is_local_db_url).
SECRET_PATTERN='-----BEGIN ([A-Z]+ )?PRIVATE KEY-----|AKIA[0-9A-Z]{16}|sk-ant-[A-Za-z0-9_-]{20,}|gh[pousr]_[A-Za-z0-9]{36}|xox[baprs]-[A-Za-z0-9-]{10,}|postgres(ql)?://[^:/@[:space:]]+:[^@[:space:]]+@[^[:space:]]+'
LOCAL_DB_URL_PATTERN='@(localhost|127\.0\.0\.1|db|postgres|db-test)[:/]|\$\{|CHANGE_ME|<[a-z_-]+>'

# Commits larger than this (excluding lockfiles, generated migrations and Markdown) need a reason.
MAX_COMMIT_LINES=400

red()  { printf '\033[31m%s\033[0m\n' "$*" >&2; }
note() { printf '%s\n' "$*" >&2; }

# validate_commit_message <first-line> ; prints a reason and returns 1 on failure.
validate_commit_message() {
  local header="$1"
  # Messages generated by git itself or by GitHub's merge button.
  if [[ "$header" =~ ^Merge\  ]] || [[ "$header" =~ ^Revert\ \" ]]; then
    return 0
  fi
  if [[ "$header" =~ ^(fixup|squash|amend)! ]]; then
    echo "fixup!/squash! commits must be folded in before they reach a shared branch"; return 1
  fi
  if (( ${#header} > MAX_HEADER_LENGTH )); then
    echo "header is ${#header} characters; keep it within ${MAX_HEADER_LENGTH}"; return 1
  fi
  if ! [[ "$header" =~ $HEADER_PATTERN ]]; then
    echo "expected '<type>(<scope>): <description>' with type one of: ${COMMIT_TYPES//|/, } and a lowercase-kebab scope"; return 1
  fi
  local description="${BASH_REMATCH[4]}"
  if ! [[ "$description" =~ ^[a-z] ]]; then
    echo "description must start with a lowercase verb, e.g. 'add', 'enforce', 'prevent'"; return 1
  fi
  if [[ "$description" =~ \.$ ]]; then
    echo "description must not end with a period"; return 1
  fi
  local words; words=$(wc -w <<<"$description")
  if (( words < MIN_DESCRIPTION_WORDS )); then
    echo "description is too vague (${words} word(s)); say what changed and where"; return 1
  fi
  if grep -qiE "$BANNED_WORDS_PATTERN" <<<"$description"; then
    echo "description uses a banned vague word (final/latest/wip/misc/...)"; return 1
  fi
  return 0
}
