// Shared error-code catalog (docs/IMPLEMENTATION_PLAN.md §12.3).
// Grows one code at a time, in the session that first throws it — this is
// the skeleton for Session 1's own errors only.
export const ERROR_CODES = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  NOT_FOUND: "NOT_FOUND",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  SERVICE_BUSY: "SERVICE_BUSY",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  FORBIDDEN: "FORBIDDEN",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  RATE_LIMITED: "RATE_LIMITED",
  IDEMPOTENCY_KEY_REQUIRED: "IDEMPOTENCY_KEY_REQUIRED",
  IDEMPOTENCY_KEY_REUSED: "IDEMPOTENCY_KEY_REUSED",
  INVALID_TRANSITION: "INVALID_TRANSITION",
  REQUEST_NOT_OPEN: "REQUEST_NOT_OPEN",
  CANCELLATION_NOT_ALLOWED: "CANCELLATION_NOT_ALLOWED",
  ACTIVE_RIDE_EXISTS: "ACTIVE_RIDE_EXISTS",
  POOL_NOT_ACCEPTING: "POOL_NOT_ACCEPTING",
  POOL_CAPACITY_EXCEEDED: "POOL_CAPACITY_EXCEEDED",
  POOL_INCOMPATIBLE: "POOL_INCOMPATIBLE",
  POOL_EMPTY: "POOL_EMPTY",
  DRIVER_OFFLINE: "DRIVER_OFFLINE",
  DRIVER_HAS_ACTIVE_POOL: "DRIVER_HAS_ACTIVE_POOL",
  ZONE_MISMATCH: "ZONE_MISMATCH",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
